//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.Application.Resources.Views.PlanningWPP {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PlanningWPP {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlanningWPP() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HMS.SKTIS.Application.Resources.Views.PlanningWPP.PlanningWPP", typeof(PlanningWPP).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string btnBrowse {
            get {
                return ResourceManager.GetString("btnBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string btnSelect {
            get {
                return ResourceManager.GetString("btnSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string btnUpload {
            get {
                return ResourceManager.GetString("btnUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error - WPP file is in older version, please contact support to get the latest version..
        /// </summary>
        public static string ExcelFormatError {
            get {
                return ResourceManager.GetString("ExcelFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error - WPP file size is too big, must be uploaded in *.xlsx format with size maximum 1MB..
        /// </summary>
        public static string FileSizeError {
            get {
                return ResourceManager.GetString("FileSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please generate group shift first..
        /// </summary>
        public static string GroupShiftNotExist {
            get {
                return ResourceManager.GetString("GroupShiftNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Family.
        /// </summary>
        public static string lblFilterBrandFamily {
            get {
                return ResourceManager.GetString("lblFilterBrandFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Group.
        /// </summary>
        public static string lblFilterBrandGroup {
            get {
                return ResourceManager.GetString("lblFilterBrandGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string lblFilterLocation {
            get {
                return ResourceManager.GetString("lblFilterLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KPS Month.
        /// </summary>
        public static string lblFilterMonth {
            get {
                return ResourceManager.GetString("lblFilterMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string lblFilterTo {
            get {
                return ResourceManager.GetString("lblFilterTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WPP File.
        /// </summary>
        public static string lblFilterUpload {
            get {
                return ResourceManager.GetString("lblFilterUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KPS Week.
        /// </summary>
        public static string lblFilterWeek {
            get {
                return ResourceManager.GetString("lblFilterWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KPS Year.
        /// </summary>
        public static string lblFilterYear {
            get {
                return ResourceManager.GetString("lblFilterYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string lblTitleBrand {
            get {
                return ResourceManager.GetString("lblTitleBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string lblTitleLocation {
            get {
                return ResourceManager.GetString("lblTitleLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error - Invalid week.
        /// </summary>
        public static string NotValidWeek {
            get {
                return ResourceManager.GetString("NotValidWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error - WPP value must be in numeric format, 0, 1, ...9.
        /// </summary>
        public static string NotValidWeekNonNumeric {
            get {
                return ResourceManager.GetString("NotValidWeekNonNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Production Planning (WPP).
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to run submit data on background process..
        /// </summary>
        public static string SubmitFailed {
            get {
                return ResourceManager.GetString("SubmitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run submit data on background process..
        /// </summary>
        public static string SubmitSuccess {
            get {
                return ResourceManager.GetString("SubmitSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand data is already expired, please check to Master -&gt; General -&gt; Brand page; .
        /// </summary>
        public static string ValidationBrandExpired {
            get {
                return ResourceManager.GetString("ValidationBrandExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand data will be expired in range 2 weeks from now, please check to Master -&gt; General -&gt; Brand page.
        /// </summary>
        public static string ValidationBrandIsWarning {
            get {
                return ResourceManager.GetString("ValidationBrandIsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location does not has selected Brand, please check to Master -&gt; General -&gt; Process Settings page; .
        /// </summary>
        public static string ValidationBrandLocation {
            get {
                return ResourceManager.GetString("ValidationBrandLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand data is not Effective, please check to Master -&gt; General -&gt; Brand Page.
        /// </summary>
        public static string ValidationBrandNotEffective {
            get {
                return ResourceManager.GetString("ValidationBrandNotEffective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand data is not found in database; .
        /// </summary>
        public static string ValidationBrandNotFound {
            get {
                return ResourceManager.GetString("ValidationBrandNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location data is inactive, please check to Master -&gt; General -&gt; Location page; .
        /// </summary>
        public static string ValidationLocationInActive {
            get {
                return ResourceManager.GetString("ValidationLocationInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location data is not found in database; .
        /// </summary>
        public static string ValidationLocationNotFound {
            get {
                return ResourceManager.GetString("ValidationLocationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WPP Value ({0}) must be in numeric format and not 0; .
        /// </summary>
        public static string ValidationValue {
            get {
                return ResourceManager.GetString("ValidationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please re-upload WPP , because there still not valid data.
        /// </summary>
        public static string ValidWPP {
            get {
                return ResourceManager.GetString("ValidWPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicking View button will cancel upload data. Click OK to continue or click Cancel to cancel..
        /// </summary>
        public static string ViewConfirmation {
            get {
                return ResourceManager.GetString("ViewConfirmation", resourceCulture);
            }
        }
    }
}
