//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.Application.Resources.Views.EquipmentRequest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EquipmentRequest {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EquipmentRequest() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HMS.SKTIS.Application.Resources.Views.EquipmentRequest.EquipmentRequest", typeof(EquipmentRequest).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Group.
        /// </summary>
        public static string lblFilterList {
            get {
                return ResourceManager.GetString("lblFilterList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string lblFilterLocation {
            get {
                return ResourceManager.GetString("lblFilterLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Qty.
        /// </summary>
        public static string lblTitleApprovedQty {
            get {
                return ResourceManager.GetString("lblTitleApprovedQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        public static string lblTitleCreatedBy {
            get {
                return ResourceManager.GetString("lblTitleCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Date.
        /// </summary>
        public static string lblTitleCreatedDate {
            get {
                return ResourceManager.GetString("lblTitleCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullfillment Qty.
        /// </summary>
        public static string lblTitleFullfillmentQty {
            get {
                return ResourceManager.GetString("lblTitleFullfillmentQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Code.
        /// </summary>
        public static string lblTitleItemCode {
            get {
                return ResourceManager.GetString("lblTitleItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Description.
        /// </summary>
        public static string lblTitleItemDescription {
            get {
                return ResourceManager.GetString("lblTitleItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Detail.
        /// </summary>
        public static string lblTitleListDetail {
            get {
                return ResourceManager.GetString("lblTitleListDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Group.
        /// </summary>
        public static string lblTitleListGroup {
            get {
                return ResourceManager.GetString("lblTitleListGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Code.
        /// </summary>
        public static string lblTitleLocationCode {
            get {
                return ResourceManager.GetString("lblTitleLocationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Description.
        /// </summary>
        public static string lblTitleLocationName {
            get {
                return ResourceManager.GetString("lblTitleLocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outstanding Qty.
        /// </summary>
        public static string lblTitleOutstandingQty {
            get {
                return ResourceManager.GetString("lblTitleOutstandingQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string lblTitleQty {
            get {
                return ResourceManager.GetString("lblTitleQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Date.
        /// </summary>
        public static string lblTitleRequestDate {
            get {
                return ResourceManager.GetString("lblTitleRequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Number.
        /// </summary>
        public static string lblTitleRequestNumber {
            get {
                return ResourceManager.GetString("lblTitleRequestNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string lblTitleStatusActive {
            get {
                return ResourceManager.GetString("lblTitleStatusActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Qty.
        /// </summary>
        public static string lblTitleTotalQty {
            get {
                return ResourceManager.GetString("lblTitleTotalQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Update.
        /// </summary>
        public static string lblTitleUpdatedBy {
            get {
                return ResourceManager.GetString("lblTitleUpdatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Date.
        /// </summary>
        public static string lblTitleUpdatedDate {
            get {
                return ResourceManager.GetString("lblTitleUpdatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Date.
        /// </summary>
        public static string lblTransactionDate {
            get {
                return ResourceManager.GetString("lblTransactionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Request.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
    }
}
