//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.Application.Resources.Views.News {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class News {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal News() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HMS.SKTIS.Application.Resources.Views.News.News", typeof(News).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string lblContent {
            get {
                return ResourceManager.GetString("lblContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content (English).
        /// </summary>
        public static string lblContentEN {
            get {
                return ResourceManager.GetString("lblContentEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content (Indonesia).
        /// </summary>
        public static string lblContentID {
            get {
                return ResourceManager.GetString("lblContentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string lblImage {
            get {
                return ResourceManager.GetString("lblImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informatips.
        /// </summary>
        public static string lblInformatips {
            get {
                return ResourceManager.GetString("lblInformatips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string lblLocation {
            get {
                return ResourceManager.GetString("lblLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Description.
        /// </summary>
        public static string lblShortDesc {
            get {
                return ResourceManager.GetString("lblShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Description (English).
        /// </summary>
        public static string lblShortDescEN {
            get {
                return ResourceManager.GetString("lblShortDescEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Description (Indonesia).
        /// </summary>
        public static string lblShortDescID {
            get {
                return ResourceManager.GetString("lblShortDescID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider.
        /// </summary>
        public static string lblSlider {
            get {
                return ResourceManager.GetString("lblSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title (English).
        /// </summary>
        public static string lblTitleEN {
            get {
                return ResourceManager.GetString("lblTitleEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title (Indonesia).
        /// </summary>
        public static string lblTitleID {
            get {
                return ResourceManager.GetString("lblTitleID", resourceCulture);
            }
        }
    }
}
