//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.Application.Resources.Views.MasterPlantEmployeeJobData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MasterPlantEmployeeJobData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MasterPlantEmployeeJobData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HMS.SKTIS.Application.Resources.Views.MasterPlantEmployeeJobData.MasterPlantEmplo" +
                            "yeeJobData", typeof(MasterPlantEmployeeJobData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Parent.
        /// </summary>
        public static string lblFilterLocation {
            get {
                return ResourceManager.GetString("lblFilterLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCT.
        /// </summary>
        public static string lblTitleCCT {
            get {
                return ResourceManager.GetString("lblTitleCCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCT Description.
        /// </summary>
        public static string lblTitleCCTDesc {
            get {
                return ResourceManager.GetString("lblTitleCCTDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string lblTitleGroup {
            get {
                return ResourceManager.GetString("lblTitleGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HCC.
        /// </summary>
        public static string lblTitleHCC {
            get {
                return ResourceManager.GetString("lblTitleHCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID.
        /// </summary>
        public static string lblTitleID {
            get {
                return ResourceManager.GetString("lblTitleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Date.
        /// </summary>
        public static string lblTitleJoin {
            get {
                return ResourceManager.GetString("lblTitleJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string lblTitleLocation {
            get {
                return ResourceManager.GetString("lblTitleLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loc ID.
        /// </summary>
        public static string lblTitleLocID {
            get {
                return ResourceManager.GetString("lblTitleLocID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string lblTitleName {
            get {
                return ResourceManager.GetString("lblTitleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Number.
        /// </summary>
        public static string lblTitleNumber {
            get {
                return ResourceManager.GetString("lblTitleNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string lblTitleProcess {
            get {
                return ResourceManager.GetString("lblTitleProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Number.
        /// </summary>
        public static string lblTitleProcessNumber {
            get {
                return ResourceManager.GetString("lblTitleProcessNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        public static string lblTitleRemark {
            get {
                return ResourceManager.GetString("lblTitleRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string lblTitleStatus {
            get {
                return ResourceManager.GetString("lblTitleStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string lblTitleUnit {
            get {
                return ResourceManager.GetString("lblTitleUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Update.
        /// </summary>
        public static string lblTitleUpdateBy {
            get {
                return ResourceManager.GetString("lblTitleUpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Date.
        /// </summary>
        public static string lblTitleUpdateDate {
            get {
                return ResourceManager.GetString("lblTitleUpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Job Data.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
    }
}
