//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrandCodeByLocationView
    {
        public string BrandCode { get; set; }
        public string BrandGroupCode { get; set; }
        public string LocationCode { get; set; }
        public Nullable<bool> StatusActive { get; set; }
        public string SKTBrandCode { get; set; }
    }
}
