//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentRequestView
    {
        public System.DateTime RequestDate { get; set; }
        public string ItemCode { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<int> ReadyToUse { get; set; }
        public Nullable<int> OnUse { get; set; }
        public Nullable<int> OnRepair { get; set; }
        public decimal TotalQty { get; set; }
        public Nullable<decimal> ApprovedQty { get; set; }
        public string LocationCode { get; set; }
        public string RequestNumber { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    }
}
