//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExeMaterialUsageView
    {
        public string LocationCode { get; set; }
        public string UnitCode { get; set; }
        public Nullable<int> Shift { get; set; }
        public string BrandGroupCode { get; set; }
        public string MaterialCode { get; set; }
        public string GroupCode { get; set; }
        public string ProcessGroup { get; set; }
        public Nullable<int> ProductionDate { get; set; }
        public Nullable<int> Sisa { get; set; }
        public Nullable<int> Ambil1 { get; set; }
        public Nullable<int> Ambil2 { get; set; }
        public Nullable<int> Ambil3 { get; set; }
        public Nullable<int> TobFM { get; set; }
        public Nullable<int> TobStem { get; set; }
        public Nullable<int> TobSapon { get; set; }
        public Nullable<int> UncountableWaste { get; set; }
        public Nullable<int> CountableWaste { get; set; }
        public Nullable<int> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> pakai { get; set; }
    }
}
