//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExeMaterialUsage
    {
        public string LocationCode { get; set; }
        public string UnitCode { get; set; }
        public int Shift { get; set; }
        public string BrandGroupCode { get; set; }
        public string MaterialCode { get; set; }
        public string GroupCode { get; set; }
        public string ProcessGroup { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public Nullable<float> Sisa { get; set; }
        public Nullable<float> Ambil1 { get; set; }
        public Nullable<float> Ambil2 { get; set; }
        public Nullable<float> Ambil3 { get; set; }
        public Nullable<float> TobFM { get; set; }
        public Nullable<float> TobStem { get; set; }
        public Nullable<float> TobSapon { get; set; }
        public Nullable<float> UncountableWaste { get; set; }
        public Nullable<float> CountableWaste { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<float> pakai { get; set; }
        public Nullable<float> Production { get; set; }
    
        public virtual MstGenBrandGroup MstGenBrandGroup { get; set; }
        public virtual MstGenMaterial MstGenMaterial { get; set; }
        public virtual MstPlantProductionGroup MstPlantProductionGroup { get; set; }
    }
}
