//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExeProductionEntryMinimumValue
    {
        public string LocationCode { get; set; }
        public int IDProcess { get; set; }
        public string BrandGroupCode { get; set; }
        public string UnitCode { get; set; }
        public string BrandCode { get; set; }
        public string ProcessGroup { get; set; }
        public string GroupCode { get; set; }
        public Nullable<int> StdStickPerHour { get; set; }
        public Nullable<int> MinimalStickPerHour { get; set; }
        public Nullable<int> UOMEblek { get; set; }
        public Nullable<int> Shift { get; set; }
    }
}
