//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExeProductionEntryPrintView
    {
        public int KPSYear { get; set; }
        public int KPSWeek { get; set; }
        public string EmployeeID { get; set; }
        public string EmployeeNumber { get; set; }
        public string MonAbsentType { get; set; }
        public string MonAbsentRemark { get; set; }
        public Nullable<decimal> MonProdCapacity { get; set; }
        public Nullable<float> MonProdTarget { get; set; }
        public Nullable<float> MonProdActual { get; set; }
        public string TueAbsentType { get; set; }
        public string TueAbsentRemark { get; set; }
        public Nullable<decimal> TueProdCapacity { get; set; }
        public Nullable<float> TueProdTarget { get; set; }
        public Nullable<float> TueProdActual { get; set; }
        public string WedAbsentType { get; set; }
        public string WedAbsentRemark { get; set; }
        public Nullable<decimal> WedProdCapacity { get; set; }
        public Nullable<float> WedProdTarget { get; set; }
        public Nullable<float> WedProdActual { get; set; }
        public string ThuAbsentType { get; set; }
        public string ThuAbsentRemark { get; set; }
        public Nullable<decimal> ThuProdCapacity { get; set; }
        public Nullable<float> ThuProdTarget { get; set; }
        public Nullable<float> ThuProdActual { get; set; }
        public string FriAbsentType { get; set; }
        public string FriAbsentRemark { get; set; }
        public Nullable<decimal> FriProdCapacity { get; set; }
        public Nullable<float> FriProdTarget { get; set; }
        public Nullable<float> FriProdActual { get; set; }
        public string SatAbsentType { get; set; }
        public string SatAbsentRemark { get; set; }
        public Nullable<decimal> SatProdCapacity { get; set; }
        public Nullable<float> SatProdTarget { get; set; }
        public Nullable<float> SatProdActual { get; set; }
        public string SunAbsentType { get; set; }
        public string SunAbsentRemark { get; set; }
        public Nullable<decimal> SunProdCapacity { get; set; }
        public Nullable<float> SunProdTarget { get; set; }
        public Nullable<float> SunProdActual { get; set; }
        public string LocationCode { get; set; }
        public string UnitCode { get; set; }
        public int Shift { get; set; }
        public string ProcessGroup { get; set; }
        public string GroupCode { get; set; }
        public string BrandCode { get; set; }
    }
}
