//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExePlantActualWorkHoursView
    {
        public string UnitCode { get; set; }
        public string LocationCode { get; set; }
        public string ProcessGroup { get; set; }
        public int ProcessOrder { get; set; }
        public string BrandCode { get; set; }
        public Nullable<int> StatusIdentifier { get; set; }
        public Nullable<int> ProductionDate { get; set; }
        public Nullable<int> Shift { get; set; }
        public Nullable<int> StatusEmp { get; set; }
        public Nullable<int> TimeIn { get; set; }
        public Nullable<int> TimeOut { get; set; }
        public Nullable<int> BreakTime { get; set; }
    }
}
