//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExePlantProductionEntry
    {
        public string ProductionEntryCode { get; set; }
        public string EmployeeID { get; set; }
        public string EmployeeNumber { get; set; }
        public string StatusEmp { get; set; }
        public int StatusIdentifier { get; set; }
        public Nullable<System.DateTime> StartDateAbsent { get; set; }
        public string AbsentType { get; set; }
        public Nullable<decimal> ProdCapacity { get; set; }
        public Nullable<float> ProdTarget { get; set; }
        public Nullable<float> ProdActual { get; set; }
        public string AbsentRemark { get; set; }
        public string AbsentCodeEblek { get; set; }
        public string AbsentCodePayroll { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> IsFromAbsenteeism { get; set; }
    
        public virtual ExePlantProductionEntryVerification ExePlantProductionEntryVerification { get; set; }
        public virtual MstPlantAbsentType MstPlantAbsentType { get; set; }
        public virtual MstPlantEmpJobsDataAll MstPlantEmpJobsDataAll { get; set; }
    }
}
