//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExePlantWorkerAbsenteeism
    {
        public System.DateTime StartDateAbsent { get; set; }
        public string EmployeeID { get; set; }
        public string AbsentType { get; set; }
        public System.DateTime EndDateAbsent { get; set; }
        public string SktAbsentCode { get; set; }
        public string PayrollAbsentCode { get; set; }
        public string ePaf { get; set; }
        public string Attachment { get; set; }
        public string AttachmentPath { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public string EmployeeNumber { get; set; }
        public string LocationCode { get; set; }
        public string UnitCode { get; set; }
        public string GroupCode { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public int Shift { get; set; }
    
        public virtual MstPlantAbsentType MstPlantAbsentType { get; set; }
        public virtual MstPlantEmpJobsDataAll MstPlantEmpJobsDataAll { get; set; }
    }
}
