//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExePlantProductionEntryVerification
    {
        public ExePlantProductionEntryVerification()
        {
            this.ExePlantProductionEntries = new HashSet<ExePlantProductionEntry>();
        }
    
        public string ProductionEntryCode { get; set; }
        public string LocationCode { get; set; }
        public string UnitCode { get; set; }
        public int Shift { get; set; }
        public string ProcessGroup { get; set; }
        public int ProcessOrder { get; set; }
        public string GroupCode { get; set; }
        public string BrandCode { get; set; }
        public int KPSYear { get; set; }
        public int KPSWeek { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public int WorkHour { get; set; }
        public Nullable<float> TPKValue { get; set; }
        public Nullable<float> TotalTargetValue { get; set; }
        public Nullable<float> TotalActualValue { get; set; }
        public Nullable<decimal> TotalCapacityValue { get; set; }
        public Nullable<bool> VerifySystem { get; set; }
        public Nullable<bool> VerifyManual { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> Flag_Manual { get; set; }
    
        public virtual ICollection<ExePlantProductionEntry> ExePlantProductionEntries { get; set; }
        public virtual ExeProductionEntryRelease ExeProductionEntryRelease { get; set; }
    }
}
