//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExePlantWorkerAssignment
    {
        public System.DateTime TransactionDate { get; set; }
        public string SourceLocationCode { get; set; }
        public string SourceUnitCode { get; set; }
        public Nullable<int> SourceShift { get; set; }
        public string SourceProcessGroup { get; set; }
        public string SourceGroupCode { get; set; }
        public string SourceBrandCode { get; set; }
        public string DestinationLocationCode { get; set; }
        public string DestinationUnitCode { get; set; }
        public Nullable<int> DestinationShift { get; set; }
        public string DestinationProcessGroup { get; set; }
        public string DestinationGroupCode { get; set; }
        public string DestinationGroupCodeDummy { get; set; }
        public string DestinationBrandCode { get; set; }
        public string EmployeeID { get; set; }
        public string EmployeeNumber { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual MstGenBrand MstGenBrand { get; set; }
        public virtual MstGenBrand MstGenBrand1 { get; set; }
        public virtual MstPlantEmpJobsDataAll MstPlantEmpJobsDataAll { get; set; }
    }
}
