//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExeReportProdStockProcessView
    {
        public string BrandGroupCode { get; set; }
        public string BrandCode { get; set; }
        public string LocationCode { get; set; }
        public string UnitCode { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public int KPSYear { get; set; }
        public int KPSWeek { get; set; }
        public Nullable<double> BeginStockInternalMove { get; set; }
        public Nullable<double> BeginStockExternalMove { get; set; }
        public Nullable<int> Production { get; set; }
        public Nullable<double> Planning { get; set; }
        public Nullable<double> VarianceStick { get; set; }
        public Nullable<double> VariancePercent { get; set; }
        public Nullable<double> PAP { get; set; }
        public Nullable<double> PAG { get; set; }
        public Nullable<double> EndingStockInternalMove { get; set; }
        public Nullable<double> EndingStockExternalMove { get; set; }
    }
}
