//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExeTPOProduction
    {
        public string ProductionEntryCode { get; set; }
        public string StatusEmp { get; set; }
        public int StatusIdentifier { get; set; }
        public string ProductionGroup { get; set; }
        public Nullable<int> WorkerCount { get; set; }
        public Nullable<int> Absent { get; set; }
        public Nullable<float> ActualProduction { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual ExeTPOProductionEntryVerification ExeTPOProductionEntryVerification { get; set; }
    }
}
