//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceEquipmentFulfillmentDetailView
    {
        public string ItemCode { get; set; }
        public string LocationCode { get; set; }
        public Nullable<int> EndingStock { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string ItemStatus { get; set; }
        public Nullable<System.DateTime> InventoryDate { get; set; }
        public string ItemDescription { get; set; }
    }
}
