//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceEquipmentStockView
    {
        public long RowID { get; set; }
        public System.DateTime InventoryDate { get; set; }
        public string ItemCode { get; set; }
        public string ItemDescription { get; set; }
        public string LocationCode { get; set; }
        public string UnitCode { get; set; }
        public Nullable<int> InTransit { get; set; }
        public Nullable<int> QI { get; set; }
        public Nullable<int> ReadyToUse { get; set; }
        public Nullable<int> BadStock { get; set; }
        public Nullable<int> TotalStockMntc { get; set; }
        public Nullable<int> Used { get; set; }
        public Nullable<int> Repair { get; set; }
        public Nullable<int> TotalStockProd { get; set; }
    }
}
