//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class MntcInventoryAdjustment
    {
        public System.DateTime AdjustmentDate { get; set; }
        public string LocationCode { get; set; }
        public string UnitCode { get; set; }
        public string UnitCodeDestination { get; set; }
        public string ItemCode { get; set; }
        public string ItemStatusFrom { get; set; }
        public string ItemStatusTo { get; set; }
        public int AdjustmentValue { get; set; }
        public string AdjustmentType { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual MstPlantUnit MstPlantUnit { get; set; }
        public virtual MstMntcItem MstMntcItem { get; set; }
    }
}
