//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class MntcEquipmentItemConvert
    {
        public System.DateTime TransactionDate { get; set; }
        public string LocationCode { get; set; }
        public string ItemCodeSource { get; set; }
        public string ItemCodeDestination { get; set; }
        public int SourceQty { get; set; }
        public Nullable<int> QtyGood { get; set; }
        public Nullable<int> QtyDisposal { get; set; }
        public bool ConversionType { get; set; }
        public Nullable<int> Shift { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public string SourceStatus { get; set; }
    
        public virtual MstGenLocation MstGenLocation { get; set; }
        public virtual MstMntcConvert MstMntcConvert { get; set; }
    }
}
