//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class MntcEquipmentMovement
    {
        public System.DateTime TransferDate { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public string LocationCodeSource { get; set; }
        public string ItemCode { get; set; }
        public string UnitCodeDestination { get; set; }
        public string LocationCodeDestination { get; set; }
        public Nullable<int> QtyTransfer { get; set; }
        public Nullable<int> QtyReceive { get; set; }
        public string TransferNote { get; set; }
        public string ReceiveNote { get; set; }
        public Nullable<int> Shift { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public string MntcMovementCode { get; set; }
    
        public virtual MstPlantUnit MstPlantUnit { get; set; }
        public virtual MstGenLocation MstGenLocation { get; set; }
        public virtual MstMntcItem MstMntcItem { get; set; }
    }
}
