//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class MntcEquipmentFulfillment
    {
        public MntcEquipmentFulfillment()
        {
            this.MntcRequestToLocations = new HashSet<MntcRequestToLocation>();
        }
    
        public System.DateTime FulFillmentDate { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public string ItemCode { get; set; }
        public string LocationCode { get; set; }
        public string RequestNumber { get; set; }
        public Nullable<decimal> RequestToQty { get; set; }
        public Nullable<decimal> PurchaseQty { get; set; }
        public string PurchaseNumber { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public string MntcReqFullFillment { get; set; }
    
        public virtual ICollection<MntcRequestToLocation> MntcRequestToLocations { get; set; }
        public virtual MntcEquipmentRequest MntcEquipmentRequest { get; set; }
    }
}
