//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstADTemp
    {
        public MstADTemp()
        {
            this.UtilDelegations = new HashSet<UtilDelegation>();
            this.UtilUsersResponsibilities = new HashSet<UtilUsersResponsibility>();
        }
    
        public string UserAD { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public Nullable<bool> StatusActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual ICollection<UtilDelegation> UtilDelegations { get; set; }
        public virtual ICollection<UtilUsersResponsibility> UtilUsersResponsibilities { get; set; }
    }
}
