//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstGenBrandGroup
    {
        public MstGenBrandGroup()
        {
            this.MstGenBrands = new HashSet<MstGenBrand>();
            this.MstGenBrandPackageItems = new HashSet<MstGenBrandPackageItem>();
            this.MstGenBrandPkgMappings = new HashSet<MstGenBrandPkgMapping>();
            this.MstGenBrandPkgMappings1 = new HashSet<MstGenBrandPkgMapping>();
            this.MstGenMaterials = new HashSet<MstGenMaterial>();
            this.MstTPOFeeRates = new HashSet<MstTPOFeeRate>();
            this.MstTPOPackages = new HashSet<MstTPOPackage>();
            this.PlanPlantIndividualCapacityReferences = new HashSet<PlanPlantIndividualCapacityReference>();
            this.MstGenProcessSettings = new HashSet<MstGenProcessSetting>();
            this.TPOFeeHdrs = new HashSet<TPOFeeHdr>();
            this.TPOFeeHdrPlans = new HashSet<TPOFeeHdrPlan>();
            this.ExeMaterialUsages = new HashSet<ExeMaterialUsage>();
            this.PlanPlantIndividualCapacityWorkHours = new HashSet<PlanPlantIndividualCapacityWorkHour>();
        }
    
        public string BrandGroupCode { get; set; }
        public string BrandFamily { get; set; }
        public string PackType { get; set; }
        public string ClassType { get; set; }
        public int StickPerPack { get; set; }
        public int PackPerSlof { get; set; }
        public int SlofPerBal { get; set; }
        public int BalPerBox { get; set; }
        public string SKTBrandCode { get; set; }
        public string Description { get; set; }
        public int CapacityPackage { get; set; }
        public Nullable<double> CigarreteWeight { get; set; }
        public int EmpPackage { get; set; }
        public Nullable<int> StickPerBox { get; set; }
        public Nullable<int> StickPerSlof { get; set; }
        public Nullable<int> StickPerBal { get; set; }
        public Nullable<bool> StatusActive { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual ICollection<MstGenBrand> MstGenBrands { get; set; }
        public virtual ICollection<MstGenBrandPackageItem> MstGenBrandPackageItems { get; set; }
        public virtual ICollection<MstGenBrandPkgMapping> MstGenBrandPkgMappings { get; set; }
        public virtual ICollection<MstGenBrandPkgMapping> MstGenBrandPkgMappings1 { get; set; }
        public virtual ICollection<MstGenMaterial> MstGenMaterials { get; set; }
        public virtual ICollection<MstTPOFeeRate> MstTPOFeeRates { get; set; }
        public virtual ICollection<MstTPOPackage> MstTPOPackages { get; set; }
        public virtual ICollection<PlanPlantIndividualCapacityReference> PlanPlantIndividualCapacityReferences { get; set; }
        public virtual ICollection<MstGenProcessSetting> MstGenProcessSettings { get; set; }
        public virtual ICollection<TPOFeeHdr> TPOFeeHdrs { get; set; }
        public virtual ICollection<TPOFeeHdrPlan> TPOFeeHdrPlans { get; set; }
        public virtual ICollection<ExeMaterialUsage> ExeMaterialUsages { get; set; }
        public virtual ICollection<PlanPlantIndividualCapacityWorkHour> PlanPlantIndividualCapacityWorkHours { get; set; }
    }
}
