//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstGenStandardHour
    {
        public string DayType { get; set; }
        public int Day { get; set; }
        public string DayName { get; set; }
        public int JknHour { get; set; }
        public int Jl1Hour { get; set; }
        public int Jl2Hour { get; set; }
        public int Jl3Hour { get; set; }
        public int Jl4Hour { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    }
}
