//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstGenLocation
    {
        public MstGenLocation()
        {
            this.MntcEquipmentItemConverts = new HashSet<MntcEquipmentItemConvert>();
            this.MntcEquipmentMovements = new HashSet<MntcEquipmentMovement>();
            this.MntcEquipmentQualityInspections = new HashSet<MntcEquipmentQualityInspection>();
            this.MntcRequestToLocations = new HashSet<MntcRequestToLocation>();
            this.MstGenHolidays = new HashSet<MstGenHoliday>();
            this.ExeReportEMSSubmitteds = new HashSet<ExeReportEMSSubmitted>();
            this.MstGenLocation1 = new HashSet<MstGenLocation>();
            this.MstGenLocStatus = new HashSet<MstGenLocStatu>();
            this.MstMntcItemLocations = new HashSet<MstMntcItemLocation>();
            this.MstPlantUnits = new HashSet<MstPlantUnit>();
            this.MstGenProcessSettingsLocations = new HashSet<MstGenProcessSettingsLocation>();
            this.NewsInfoes = new HashSet<NewsInfo>();
            this.PlanTPOTargetProductionKelompokBoxes = new HashSet<PlanTPOTargetProductionKelompokBox>();
            this.PlanWeeklyProductionPlannings = new HashSet<PlanWeeklyProductionPlanning>();
        }
    
        public string LocationCode { get; set; }
        public string LocationName { get; set; }
        public string ParentLocationCode { get; set; }
        public string CostCenter { get; set; }
        public string ABBR { get; set; }
        public Nullable<int> Shift { get; set; }
        public Nullable<decimal> UMK { get; set; }
        public string KPPBC { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> StatusActive { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual ICollection<MntcEquipmentItemConvert> MntcEquipmentItemConverts { get; set; }
        public virtual ICollection<MntcEquipmentMovement> MntcEquipmentMovements { get; set; }
        public virtual ICollection<MntcEquipmentQualityInspection> MntcEquipmentQualityInspections { get; set; }
        public virtual ICollection<MntcRequestToLocation> MntcRequestToLocations { get; set; }
        public virtual ICollection<MstGenHoliday> MstGenHolidays { get; set; }
        public virtual ICollection<ExeReportEMSSubmitted> ExeReportEMSSubmitteds { get; set; }
        public virtual ICollection<MstGenLocation> MstGenLocation1 { get; set; }
        public virtual MstGenLocation MstGenLocation2 { get; set; }
        public virtual ICollection<MstGenLocStatu> MstGenLocStatus { get; set; }
        public virtual ICollection<MstMntcItemLocation> MstMntcItemLocations { get; set; }
        public virtual ICollection<MstPlantUnit> MstPlantUnits { get; set; }
        public virtual MstTPOInfo MstTPOInfo { get; set; }
        public virtual ICollection<MstGenProcessSettingsLocation> MstGenProcessSettingsLocations { get; set; }
        public virtual ICollection<NewsInfo> NewsInfoes { get; set; }
        public virtual ICollection<PlanTPOTargetProductionKelompokBox> PlanTPOTargetProductionKelompokBoxes { get; set; }
        public virtual ICollection<PlanWeeklyProductionPlanning> PlanWeeklyProductionPlannings { get; set; }
    }
}
