//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstGenBrand
    {
        public MstGenBrand()
        {
            this.ExeActualWorkHours = new HashSet<ExeActualWorkHour>();
            this.ExeTPOActualWorkHours = new HashSet<ExeTPOActualWorkHour>();
            this.ExePlantCKSubmits = new HashSet<ExePlantCKSubmit>();
            this.ExeReportEMSSubmitteds = new HashSet<ExeReportEMSSubmitted>();
            this.PlanPlantTargetProductionKelompoks = new HashSet<PlanPlantTargetProductionKelompok>();
            this.ProductAdjustments = new HashSet<ProductAdjustment>();
            this.ExeReportByProcesses = new HashSet<ExeReportByProcess>();
            this.ProductionCards = new HashSet<ProductionCard>();
            this.PlanTPOTargetProductionKelompoks = new HashSet<PlanTPOTargetProductionKelompok>();
            this.PlanTPOTargetProductionKelompokBoxes = new HashSet<PlanTPOTargetProductionKelompokBox>();
            this.PlanWeeklyProductionPlannings = new HashSet<PlanWeeklyProductionPlanning>();
            this.ExeReportByGroupsWeeklies = new HashSet<ExeReportByGroupsWeekly>();
            this.ExeReportByGroupsMonthlies = new HashSet<ExeReportByGroupsMonthly>();
            this.ExePlantWorkerAssignments = new HashSet<ExePlantWorkerAssignment>();
            this.ExePlantWorkerAssignments1 = new HashSet<ExePlantWorkerAssignment>();
            this.ExeReportByGroups = new HashSet<ExeReportByGroup>();
        }
    
        public string BrandCode { get; set; }
        public string BrandGroupCode { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual ICollection<ExeActualWorkHour> ExeActualWorkHours { get; set; }
        public virtual ICollection<ExeTPOActualWorkHour> ExeTPOActualWorkHours { get; set; }
        public virtual ICollection<ExePlantCKSubmit> ExePlantCKSubmits { get; set; }
        public virtual ICollection<ExeReportEMSSubmitted> ExeReportEMSSubmitteds { get; set; }
        public virtual MstGenBrandGroup MstGenBrandGroup { get; set; }
        public virtual ICollection<PlanPlantTargetProductionKelompok> PlanPlantTargetProductionKelompoks { get; set; }
        public virtual ICollection<ProductAdjustment> ProductAdjustments { get; set; }
        public virtual ICollection<ExeReportByProcess> ExeReportByProcesses { get; set; }
        public virtual ICollection<ProductionCard> ProductionCards { get; set; }
        public virtual ICollection<PlanTPOTargetProductionKelompok> PlanTPOTargetProductionKelompoks { get; set; }
        public virtual ICollection<PlanTPOTargetProductionKelompokBox> PlanTPOTargetProductionKelompokBoxes { get; set; }
        public virtual ICollection<PlanWeeklyProductionPlanning> PlanWeeklyProductionPlannings { get; set; }
        public virtual ICollection<ExeReportByGroupsWeekly> ExeReportByGroupsWeeklies { get; set; }
        public virtual ICollection<ExeReportByGroupsMonthly> ExeReportByGroupsMonthlies { get; set; }
        public virtual ICollection<ExePlantWorkerAssignment> ExePlantWorkerAssignments { get; set; }
        public virtual ICollection<ExePlantWorkerAssignment> ExePlantWorkerAssignments1 { get; set; }
        public virtual ICollection<ExeReportByGroup> ExeReportByGroups { get; set; }
    }
}
