//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstGenProcessSetting
    {
        public MstGenProcessSetting()
        {
            this.MstGenProcessSettingsLocations = new HashSet<MstGenProcessSettingsLocation>();
        }
    
        public long ID { get; set; }
        public int IDProcess { get; set; }
        public string BrandGroupCode { get; set; }
        public string ProcessGroup { get; set; }
        public Nullable<int> StdStickPerHour { get; set; }
        public Nullable<int> MinStickPerHour { get; set; }
        public Nullable<int> UOMEblek { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> MaxWorker { get; set; }
    
        public virtual MstGenBrandGroup MstGenBrandGroup { get; set; }
        public virtual MstGenProcess MstGenProcess { get; set; }
        public virtual ICollection<MstGenProcessSettingsLocation> MstGenProcessSettingsLocations { get; set; }
    }
}
