//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstMntcConvert
    {
        public MstMntcConvert()
        {
            this.MntcEquipmentItemConverts = new HashSet<MntcEquipmentItemConvert>();
        }
    
        public string ItemCodeSource { get; set; }
        public string ItemCodeDestination { get; set; }
        public Nullable<bool> ConversionType { get; set; }
        public Nullable<int> QtyConvert { get; set; }
        public Nullable<bool> StatusActive { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual ICollection<MntcEquipmentItemConvert> MntcEquipmentItemConverts { get; set; }
        public virtual MstMntcItem MstMntcItem { get; set; }
        public virtual MstMntcItem MstMntcItem1 { get; set; }
    }
}
