//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstMntcItem
    {
        public MstMntcItem()
        {
            this.MntcEquipmentMovements = new HashSet<MntcEquipmentMovement>();
            this.MntcEquipmentQualityInspections = new HashSet<MntcEquipmentQualityInspection>();
            this.MntcEquipmentRepairs = new HashSet<MntcEquipmentRepair>();
            this.MstGenBrandPackageItems = new HashSet<MstGenBrandPackageItem>();
            this.MstMntcConverts = new HashSet<MstMntcConvert>();
            this.MstMntcConverts1 = new HashSet<MstMntcConvert>();
            this.MstMntcItemLocations = new HashSet<MstMntcItemLocation>();
            this.MntcRepairItemUsages = new HashSet<MntcRepairItemUsage>();
            this.MntcInventoryAdjustments = new HashSet<MntcInventoryAdjustment>();
        }
    
        public string ItemCode { get; set; }
        public string ItemDescription { get; set; }
        public string ItemType { get; set; }
        public string UOM { get; set; }
        public string PriceType { get; set; }
        public Nullable<bool> StatusActive { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual ICollection<MntcEquipmentMovement> MntcEquipmentMovements { get; set; }
        public virtual ICollection<MntcEquipmentQualityInspection> MntcEquipmentQualityInspections { get; set; }
        public virtual ICollection<MntcEquipmentRepair> MntcEquipmentRepairs { get; set; }
        public virtual ICollection<MstGenBrandPackageItem> MstGenBrandPackageItems { get; set; }
        public virtual ICollection<MstMntcConvert> MstMntcConverts { get; set; }
        public virtual ICollection<MstMntcConvert> MstMntcConverts1 { get; set; }
        public virtual ICollection<MstMntcItemLocation> MstMntcItemLocations { get; set; }
        public virtual ICollection<MntcRepairItemUsage> MntcRepairItemUsages { get; set; }
        public virtual ICollection<MntcInventoryAdjustment> MntcInventoryAdjustments { get; set; }
    }
}
