//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstMntcConvertGetItemDestinationView
    {
        public string ItemCode { get; set; }
        public string ItemCodeDest { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<int> Qty { get; set; }
    }
}
