//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstPlantProductionGroup
    {
        public MstPlantProductionGroup()
        {
            this.ExeMaterialUsages = new HashSet<ExeMaterialUsage>();
            this.MstPlantProductionGroup1 = new HashSet<MstPlantProductionGroup>();
            this.PlanPlantLineBalancings = new HashSet<PlanPlantLineBalancing>();
            this.PlanPlantTargetProductionKelompoks = new HashSet<PlanPlantTargetProductionKelompok>();
            this.PlanPlantWorkerBalancings = new HashSet<PlanPlantWorkerBalancing>();
            this.PlanPlantWorkerBalancings1 = new HashSet<PlanPlantWorkerBalancing>();
            this.ProductionCards = new HashSet<ProductionCard>();
            this.PlanPlantIndividualCapacityWorkHours = new HashSet<PlanPlantIndividualCapacityWorkHour>();
        }
    
        public string GroupCode { get; set; }
        public string UnitCode { get; set; }
        public string LocationCode { get; set; }
        public string ProcessGroup { get; set; }
        public string InspectionLeader { get; set; }
        public string Leader1 { get; set; }
        public string Leader2 { get; set; }
        public string NextGroupCode { get; set; }
        public string Mst_UnitCode { get; set; }
        public string Mst_LocationCode { get; set; }
        public string Mst_ProcessGroup { get; set; }
        public string AvailableNumbers { get; set; }
        public Nullable<int> WorkerCount { get; set; }
        public Nullable<bool> StatusActive { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual ICollection<ExeMaterialUsage> ExeMaterialUsages { get; set; }
        public virtual MstGenProcess MstGenProcess { get; set; }
        public virtual ICollection<MstPlantProductionGroup> MstPlantProductionGroup1 { get; set; }
        public virtual MstPlantProductionGroup MstPlantProductionGroup2 { get; set; }
        public virtual MstPlantUnit MstPlantUnit { get; set; }
        public virtual ICollection<PlanPlantLineBalancing> PlanPlantLineBalancings { get; set; }
        public virtual ICollection<PlanPlantTargetProductionKelompok> PlanPlantTargetProductionKelompoks { get; set; }
        public virtual ICollection<PlanPlantWorkerBalancing> PlanPlantWorkerBalancings { get; set; }
        public virtual ICollection<PlanPlantWorkerBalancing> PlanPlantWorkerBalancings1 { get; set; }
        public virtual ICollection<ProductionCard> ProductionCards { get; set; }
        public virtual MstPlantEmpJobsDataAll MstPlantEmpJobsDataAll { get; set; }
        public virtual MstPlantEmpJobsDataAll MstPlantEmpJobsDataAll1 { get; set; }
        public virtual MstPlantEmpJobsDataAll MstPlantEmpJobsDataAll2 { get; set; }
        public virtual ICollection<PlanPlantIndividualCapacityWorkHour> PlanPlantIndividualCapacityWorkHours { get; set; }
    }
}
