//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstPlantProductionGroupView
    {
        public long RowID { get; set; }
        public string GroupCode { get; set; }
        public string LocationCode { get; set; }
        public string UnitCode { get; set; }
        public string ProcessSettingsCode { get; set; }
        public Nullable<int> WorkerCount { get; set; }
        public string Leader1 { get; set; }
        public string Leader2 { get; set; }
        public string InspectionLeader { get; set; }
        public string NextGroupCode { get; set; }
        public Nullable<bool> StatusActive { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public string LeaderInspectionName { get; set; }
        public string Leader1Name { get; set; }
        public string Leader2Name { get; set; }
    }
}
