//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstPlantEmpJobsDataAll
    {
        public MstPlantEmpJobsDataAll()
        {
            this.ExePlantProductionEntries = new HashSet<ExePlantProductionEntry>();
            this.ExePlantWorkerAbsenteeism = new HashSet<ExePlantWorkerAbsenteeism>();
            this.ExePlantWorkerAssignments = new HashSet<ExePlantWorkerAssignment>();
            this.MstPlantProductionGroups = new HashSet<MstPlantProductionGroup>();
            this.MstPlantProductionGroups1 = new HashSet<MstPlantProductionGroup>();
            this.MstPlantProductionGroups2 = new HashSet<MstPlantProductionGroup>();
            this.PlanPlantIndividualCapacityReferences = new HashSet<PlanPlantIndividualCapacityReference>();
            this.PlanPlantAllocations = new HashSet<PlanPlantAllocation>();
            this.PlanPlantIndividualCapacityWorkHours = new HashSet<PlanPlantIndividualCapacityWorkHour>();
            this.PlanPlantWorkerBalancings = new HashSet<PlanPlantWorkerBalancing>();
            this.ProductionCards = new HashSet<ProductionCard>();
        }
    
        public string EmployeeID { get; set; }
        public string EmployeeNumber { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public string TitleID { get; set; }
        public string ProcessSettingsCode { get; set; }
        public string Status { get; set; }
        public string CCT { get; set; }
        public string CCTDescription { get; set; }
        public string HCC { get; set; }
        public string LocationCode { get; set; }
        public string GroupCode { get; set; }
        public string UnitCode { get; set; }
        public string Loc_id { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual ICollection<ExePlantProductionEntry> ExePlantProductionEntries { get; set; }
        public virtual ICollection<ExePlantWorkerAbsenteeism> ExePlantWorkerAbsenteeism { get; set; }
        public virtual ICollection<ExePlantWorkerAssignment> ExePlantWorkerAssignments { get; set; }
        public virtual MstPlantEmpJobsDataAcv MstPlantEmpJobsDataAcv { get; set; }
        public virtual ICollection<MstPlantProductionGroup> MstPlantProductionGroups { get; set; }
        public virtual ICollection<MstPlantProductionGroup> MstPlantProductionGroups1 { get; set; }
        public virtual ICollection<MstPlantProductionGroup> MstPlantProductionGroups2 { get; set; }
        public virtual ICollection<PlanPlantIndividualCapacityReference> PlanPlantIndividualCapacityReferences { get; set; }
        public virtual ICollection<PlanPlantAllocation> PlanPlantAllocations { get; set; }
        public virtual ICollection<PlanPlantIndividualCapacityWorkHour> PlanPlantIndividualCapacityWorkHours { get; set; }
        public virtual ICollection<PlanPlantWorkerBalancing> PlanPlantWorkerBalancings { get; set; }
        public virtual ICollection<ProductionCard> ProductionCards { get; set; }
    }
}
