//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstTPOProductionGroup
    {
        public MstTPOProductionGroup()
        {
            this.PlanTPOTargetProductionKelompoks = new HashSet<PlanTPOTargetProductionKelompok>();
        }
    
        public string ProdGroup { get; set; }
        public string ProcessGroup { get; set; }
        public string LocationCode { get; set; }
        public string StatusEmp { get; set; }
        public Nullable<bool> StatusActive { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> WorkerCount { get; set; }
    
        public virtual MstGenLocStatu MstGenLocStatu { get; set; }
        public virtual MstGenProcess MstGenProcess { get; set; }
        public virtual ICollection<PlanTPOTargetProductionKelompok> PlanTPOTargetProductionKelompoks { get; set; }
    }
}
