//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstTPOInfo
    {
        public MstTPOInfo()
        {
            this.MstTPOFeeRates = new HashSet<MstTPOFeeRate>();
            this.MstTPOPackages = new HashSet<MstTPOPackage>();
            this.TPOFeeHdrs = new HashSet<TPOFeeHdr>();
            this.TPOFeeHdrPlans = new HashSet<TPOFeeHdrPlan>();
        }
    
        public string LocationCode { get; set; }
        public string TPORank { get; set; }
        public string Owner { get; set; }
        public string VendorNumber { get; set; }
        public string VendorName { get; set; }
        public string BankType { get; set; }
        public string BankAccountNumber { get; set; }
        public string BankAccountName { get; set; }
        public string BankBranch { get; set; }
        public Nullable<System.DateTime> Established { get; set; }
        public Nullable<bool> StatusActive { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual MstGenLocation MstGenLocation { get; set; }
        public virtual ICollection<MstTPOFeeRate> MstTPOFeeRates { get; set; }
        public virtual ICollection<MstTPOPackage> MstTPOPackages { get; set; }
        public virtual ICollection<TPOFeeHdr> TPOFeeHdrs { get; set; }
        public virtual ICollection<TPOFeeHdrPlan> TPOFeeHdrPlans { get; set; }
    }
}
