//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstTPOPackage
    {
        public string LocationCode { get; set; }
        public string BrandGroupCode { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public System.DateTime ExpiredDate { get; set; }
        public float Package { get; set; }
        public string MemoRef { get; set; }
        public string MemoFile { get; set; }
        public string MemoPath { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual MstGenBrandGroup MstGenBrandGroup { get; set; }
        public virtual MstTPOInfo MstTPOInfo { get; set; }
    }
}
