//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsInfo
    {
        public int NewsId { get; set; }
        public string TitleID { get; set; }
        public string TitleEN { get; set; }
        public string ShortDescriptionID { get; set; }
        public string ShortDescriptionEN { get; set; }
        public string ContentID { get; set; }
        public string ContentEN { get; set; }
        public string Image { get; set; }
        public Nullable<bool> IsSlider { get; set; }
        public Nullable<bool> IsInformatips { get; set; }
        public string Location { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual MstGenLocation MstGenLocation { get; set; }
    }
}
