//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanPlantLineBalancing
    {
        public PlanPlantLineBalancing()
        {
            this.PlanPlantWorkerBalancings = new HashSet<PlanPlantWorkerBalancing>();
        }
    
        public System.DateTime ProductionDate { get; set; }
        public Nullable<int> IDProcess { get; set; }
        public string ProcessIdentifier { get; set; }
        public string Mst_LocationCode { get; set; }
        public string GroupCode { get; set; }
        public string UnitCode { get; set; }
        public string LocationCode { get; set; }
        public string ProcessGroup { get; set; }
        public Nullable<int> CurrentValue { get; set; }
        public Nullable<int> AfterBalancing { get; set; }
        public Nullable<int> SystemRecommendation { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual ICollection<PlanPlantWorkerBalancing> PlanPlantWorkerBalancings { get; set; }
        public virtual MstPlantProductionGroup MstPlantProductionGroup { get; set; }
    }
}
