//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanPlantTargetProductionKelompokView
    {
        public string BrandCode { get; set; }
        public string LocationCode { get; set; }
        public Nullable<double> TargetSystem1 { get; set; }
        public Nullable<double> TargetSystem2 { get; set; }
        public Nullable<double> TargetSystem3 { get; set; }
        public Nullable<double> TargetSystem4 { get; set; }
        public Nullable<double> TargetSystem5 { get; set; }
        public Nullable<double> TargetSystem6 { get; set; }
        public Nullable<double> TargetSystem7 { get; set; }
    }
}
