//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanPlantWIPDetail
    {
        public int KPSYear { get; set; }
        public int KPSWeek { get; set; }
        public string ProcessGroup { get; set; }
        public string UnitCode { get; set; }
        public string LocationCode { get; set; }
        public string BrandCode { get; set; }
        public Nullable<int> WIPCurrentValue { get; set; }
        public Nullable<int> WIPPreviousValue { get; set; }
        public Nullable<int> WIPStock1 { get; set; }
        public Nullable<int> WIPStock2 { get; set; }
        public Nullable<int> WIPStock3 { get; set; }
        public Nullable<int> WIPStock4 { get; set; }
        public Nullable<int> WIPStock5 { get; set; }
        public Nullable<int> WIPStock6 { get; set; }
        public Nullable<int> WIPStock7 { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    }
}
