//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanPlantAllocation
    {
        public int KPSYear { get; set; }
        public int KPSWeek { get; set; }
        public string GroupCode { get; set; }
        public string ProcessGroup { get; set; }
        public string UnitCode { get; set; }
        public string LocationCode { get; set; }
        public string BrandCode { get; set; }
        public int Shift { get; set; }
        public System.DateTime TPKPlantStartProductionDate { get; set; }
        public string EmployeeID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual MstPlantEmpJobsDataAll MstPlantEmpJobsDataAll { get; set; }
        public virtual PlanPlantTargetProductionKelompok PlanPlantTargetProductionKelompok { get; set; }
    }
}
