//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanPlantWorkerBalancing
    {
        public System.DateTime BalancingDate { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public string EmployeeID { get; set; }
        public string GroupCodeSource { get; set; }
        public string UnitCodeSource { get; set; }
        public string LocationCodeSource { get; set; }
        public string ProcessGroupSource { get; set; }
        public string GroupCodeDestination { get; set; }
        public string UnitCodeDestination { get; set; }
        public string LocationCodeDestination { get; set; }
        public string ProcessGroupDestination { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual PlanPlantLineBalancing PlanPlantLineBalancing { get; set; }
        public virtual MstPlantProductionGroup MstPlantProductionGroup { get; set; }
        public virtual MstPlantProductionGroup MstPlantProductionGroup1 { get; set; }
        public virtual MstPlantEmpJobsDataAll MstPlantEmpJobsDataAll { get; set; }
    }
}
