//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessSettingsAndLocationView
    {
        public string LocationCode { get; set; }
        public int IDProcess { get; set; }
        public string BrandGroupCode { get; set; }
        public string ProcessGroup { get; set; }
        public Nullable<int> StdStickPerHour { get; set; }
        public Nullable<int> MinStickPerHour { get; set; }
        public Nullable<int> UOMEblek { get; set; }
        public string LocationName { get; set; }
        public string ParentLocationCode { get; set; }
        public string CostCenter { get; set; }
        public string ABBR { get; set; }
        public Nullable<int> Shift { get; set; }
        public Nullable<decimal> UMK { get; set; }
        public string KPPBC { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> StatusActiveLocation { get; set; }
        public string ProcessIdentifier { get; set; }
        public int ProcessOrder { get; set; }
        public Nullable<bool> StatusActiveProcess { get; set; }
        public bool WIP { get; set; }
        public string BrandFamily { get; set; }
        public string PackType { get; set; }
        public string ClassType { get; set; }
        public int StickPerPack { get; set; }
        public int PackPerSlof { get; set; }
        public int SlofPerBal { get; set; }
        public int BalPerBox { get; set; }
        public string SKTBrandCode { get; set; }
        public string Description { get; set; }
        public int CapacityPackage { get; set; }
        public Nullable<double> CigarreteWeight { get; set; }
        public int EmpPackage { get; set; }
        public Nullable<int> StickPerBox { get; set; }
        public Nullable<int> StickPerSlof { get; set; }
        public Nullable<int> StickPerBal { get; set; }
        public Nullable<bool> StatusActiveBrand { get; set; }
    }
}
