//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductAdjustment
    {
        public System.DateTime ProductionDate { get; set; }
        public string UnitCode { get; set; }
        public string LocationCode { get; set; }
        public int Shift { get; set; }
        public string BrandCode { get; set; }
        public string ProcessGroup { get; set; }
        public string AdjustmentType { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> AdjustmentValue { get; set; }
        public string AdjustmentRemark { get; set; }
        public string StatusEmp { get; set; }
        public string StatusIdentifier { get; set; }
        public string GroupCode { get; set; }
    
        public virtual MstGenBrand MstGenBrand { get; set; }
        public virtual MstGenEmpStatu MstGenEmpStatu { get; set; }
        public virtual MstGenProcess MstGenProcess { get; set; }
        public virtual MstPlantUnit MstPlantUnit { get; set; }
    }
}
