//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionCard
    {
        public int RevisionType { get; set; }
        public string LocationCode { get; set; }
        public string UnitCode { get; set; }
        public Nullable<int> Shift { get; set; }
        public string BrandCode { get; set; }
        public string BrandGroupCode { get; set; }
        public string ProcessGroup { get; set; }
        public string GroupCode { get; set; }
        public string EmployeeID { get; set; }
        public string EmployeeNumber { get; set; }
        public Nullable<float> Production { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public Nullable<int> WorkHours { get; set; }
        public string Absent { get; set; }
        public Nullable<float> UpahLain { get; set; }
        public string EblekAbsentType { get; set; }
        public string Remark { get; set; }
        public string Comments { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public string ProductionCardCode { get; set; }
    
        public virtual MstGenBrand MstGenBrand { get; set; }
        public virtual MstPlantProductionGroup MstPlantProductionGroup { get; set; }
        public virtual MstPlantEmpJobsDataAll MstPlantEmpJobsDataAll { get; set; }
    }
}
