//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tmp_MstGenBrandGroup
    {
        public string BrandGroupCode { get; set; }
        public string BrandFamily { get; set; }
        public string PackType { get; set; }
        public string ClassType { get; set; }
        public int StickPerPack { get; set; }
        public int PackPerSlof { get; set; }
        public int SlofPerBal { get; set; }
        public int BalPerBox { get; set; }
        public string SKTBrandCode { get; set; }
        public string Description { get; set; }
        public int CapacityPackage { get; set; }
        public Nullable<double> CigarreteWeight { get; set; }
        public int EmpPackage { get; set; }
        public Nullable<int> StickPerBox { get; set; }
        public Nullable<int> StickPerSlof { get; set; }
        public Nullable<int> StickPerBal { get; set; }
        public Nullable<bool> StatusActive { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    }
}
