//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPOFeeHdrPlan
    {
        public TPOFeeHdrPlan()
        {
            this.TPOFeeCalculationPlans = new HashSet<TPOFeeCalculationPlan>();
            this.TPOFeeProductionDailyPlans = new HashSet<TPOFeeProductionDailyPlan>();
        }
    
        public string TPOFeeCode { get; set; }
        public int KPSYear { get; set; }
        public int KPSWeek { get; set; }
        public string BrandGroupCode { get; set; }
        public string LocationCode { get; set; }
        public Nullable<int> TPOFeeTempID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public string Status { get; set; }
        public Nullable<int> StickPerBox { get; set; }
        public Nullable<double> TPOPackageValue { get; set; }
        public Nullable<double> TotalProdStick { get; set; }
        public Nullable<double> TotalProdBox { get; set; }
        public Nullable<double> TotalProdJKN { get; set; }
        public Nullable<double> TotalProdJl1 { get; set; }
        public Nullable<double> TotalProdJl2 { get; set; }
        public Nullable<double> TotalProdJl3 { get; set; }
        public Nullable<double> TotalProdJl4 { get; set; }
    
        public virtual MstGenBrandGroup MstGenBrandGroup { get; set; }
        public virtual MstTPOInfo MstTPOInfo { get; set; }
        public virtual ICollection<TPOFeeCalculationPlan> TPOFeeCalculationPlans { get; set; }
        public virtual ICollection<TPOFeeProductionDailyPlan> TPOFeeProductionDailyPlans { get; set; }
    }
}
