//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class TpoFeePlanView
    {
        public string LocationCode { get; set; }
        public string LocationName { get; set; }
        public string SKTBrandCode { get; set; }
        public string TPOFeeCode { get; set; }
        public string ProductionFeeType { get; set; }
        public Nullable<int> KPSYear { get; set; }
        public Nullable<int> KPSWeek { get; set; }
        public Nullable<int> OrderFeeType { get; set; }
        public Nullable<double> OutputProduction { get; set; }
        public Nullable<double> OutputBiaya { get; set; }
        public Nullable<double> Calculate { get; set; }
    }
}
