//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPOFeeReportsProductionDailyView
    {
        public string TPOFeeCode { get; set; }
        public System.DateTime FeeDate { get; set; }
        public string Regional { get; set; }
        public string LocationCode { get; set; }
        public string LocationAbbr { get; set; }
        public string LocationName { get; set; }
        public Nullable<decimal> UMK { get; set; }
        public string Brand { get; set; }
        public Nullable<float> Package { get; set; }
        public Nullable<double> JKNProductionFee { get; set; }
        public Nullable<double> JL1ProductionFee { get; set; }
        public Nullable<double> JL2ProductionFee { get; set; }
        public Nullable<double> JL3ProductionFee { get; set; }
        public Nullable<double> JL4ProductionFee { get; set; }
        public Nullable<double> ManagementFee { get; set; }
        public Nullable<decimal> ProductivityIncentives { get; set; }
        public int Year { get; set; }
        public int Week { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string NoMemo { get; set; }
        public Nullable<double> JKNProductionVolume { get; set; }
        public Nullable<double> JL1ProductionVolume { get; set; }
        public Nullable<double> JL2ProductionVolume { get; set; }
        public Nullable<double> JL3ProductionVolume { get; set; }
        public Nullable<double> JL4ProductionVolume { get; set; }
    }
}
