//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPOTargetProductionKelompokView
    {
        public System.DateTime TPKTPOStartProductionDate { get; set; }
        public int KPSYear { get; set; }
        public int KPSWeek { get; set; }
        public string ProdGroup { get; set; }
        public string ProcessGroup { get; set; }
        public string LocationCode { get; set; }
        public string StatusEmp { get; set; }
        public string BrandCode { get; set; }
        public string TPKCode { get; set; }
        public Nullable<int> WorkerRegister { get; set; }
        public Nullable<int> WorkerAvailable { get; set; }
        public Nullable<int> WorkerAlocation { get; set; }
        public Nullable<int> WIPStock { get; set; }
        public Nullable<float> PercentAttendance1 { get; set; }
        public Nullable<float> PercentAttendance2 { get; set; }
        public Nullable<float> PercentAttendance3 { get; set; }
        public Nullable<float> PercentAttendance4 { get; set; }
        public Nullable<float> PercentAttendance5 { get; set; }
        public Nullable<float> PercentAttendance6 { get; set; }
        public Nullable<float> PercentAttendance7 { get; set; }
        public Nullable<float> HistoricalCapacityWorker1 { get; set; }
        public Nullable<float> HistoricalCapacityWorker2 { get; set; }
        public Nullable<float> HistoricalCapacityWorker3 { get; set; }
        public Nullable<float> HistoricalCapacityWorker4 { get; set; }
        public Nullable<float> HistoricalCapacityWorker5 { get; set; }
        public Nullable<float> HistoricalCapacityWorker6 { get; set; }
        public Nullable<float> HistoricalCapacityWorker7 { get; set; }
        public Nullable<float> HistoricalCapacityGroup1 { get; set; }
        public Nullable<float> HistoricalCapacityGroup2 { get; set; }
        public Nullable<float> HistoricalCapacityGroup3 { get; set; }
        public Nullable<float> HistoricalCapacityGroup4 { get; set; }
        public Nullable<float> HistoricalCapacityGroup5 { get; set; }
        public Nullable<float> HistoricalCapacityGroup6 { get; set; }
        public Nullable<float> HistoricalCapacityGroup7 { get; set; }
        public Nullable<float> TargetSystem1 { get; set; }
        public Nullable<float> TargetSystem2 { get; set; }
        public Nullable<float> TargetSystem3 { get; set; }
        public Nullable<float> TargetSystem4 { get; set; }
        public Nullable<float> TargetSystem5 { get; set; }
        public Nullable<float> TargetSystem6 { get; set; }
        public Nullable<float> TargetSystem7 { get; set; }
        public Nullable<float> TargetManual1 { get; set; }
        public Nullable<float> TargetManual2 { get; set; }
        public Nullable<float> TargetManual3 { get; set; }
        public Nullable<float> TargetManual4 { get; set; }
        public Nullable<float> TargetManual5 { get; set; }
        public Nullable<float> TargetManual6 { get; set; }
        public Nullable<float> TargetManual7 { get; set; }
        public Nullable<float> ProcessWorkHours1 { get; set; }
        public Nullable<float> ProcessWorkHours2 { get; set; }
        public Nullable<float> ProcessWorkHours3 { get; set; }
        public Nullable<float> ProcessWorkHours4 { get; set; }
        public Nullable<float> ProcessWorkHours5 { get; set; }
        public Nullable<float> ProcessWorkHours6 { get; set; }
        public Nullable<float> ProcessWorkHours7 { get; set; }
        public Nullable<float> TotalWorkhours { get; set; }
        public Nullable<float> TotalTargetSystem { get; set; }
        public Nullable<float> TotalTargetManual { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> WIP1 { get; set; }
        public Nullable<int> WIP2 { get; set; }
        public Nullable<int> WIP3 { get; set; }
        public Nullable<int> WIP4 { get; set; }
        public Nullable<int> WIP5 { get; set; }
        public Nullable<int> WIP6 { get; set; }
        public Nullable<int> WIP7 { get; set; }
        public Nullable<int> TotalWorkHours1Prev3Weeks { get; set; }
        public Nullable<int> TotalWorkHours2Prev3Weeks { get; set; }
        public Nullable<int> TotalWorkHours3Prev3Weeks { get; set; }
        public Nullable<int> TotalWorkHours4Prev3Weeks { get; set; }
        public Nullable<int> TotalWorkHours5Prev3Weeks { get; set; }
        public Nullable<int> TotalWorkHours6Prev3Weeks { get; set; }
        public Nullable<int> TotalWorkHours7Prev3Weeks { get; set; }
        public Nullable<int> TotalActualProductionPrev3Weeks { get; set; }
        public int ProcessOrder { get; set; }
    }
}
