//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserADResponsibilityRolesView
    {
        public string UserAD { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public Nullable<bool> StatusActive { get; set; }
        public int IDResponsibility { get; set; }
        public string ResponsibilityName { get; set; }
        public int IDRole { get; set; }
        public string RolesCode { get; set; }
        public string RolesName { get; set; }
    }
}
