//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class UtilRolesFunction
    {
        public UtilRolesFunction()
        {
            this.UtilFlows = new HashSet<UtilFlow>();
        }
    
        public int IDFunction { get; set; }
        public int IDRole { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual ICollection<UtilFlow> UtilFlows { get; set; }
        public virtual UtilFunction UtilFunction { get; set; }
        public virtual UtilRole UtilRole { get; set; }
    }
}
