//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class UtilResponsibility
    {
        public UtilResponsibility()
        {
            this.UtilResponsibilityRules = new HashSet<UtilResponsibilityRule>();
            this.UtilUsersResponsibilities = new HashSet<UtilUsersResponsibility>();
        }
    
        public int IDResponsibility { get; set; }
        public Nullable<int> IDRole { get; set; }
        public string ResponsibilityName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
    
        public virtual UtilRole UtilRole { get; set; }
        public virtual ICollection<UtilResponsibilityRule> UtilResponsibilityRules { get; set; }
        public virtual ICollection<UtilUsersResponsibility> UtilUsersResponsibilities { get; set; }
    }
}
