//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class UtilFlowFunctionView
    {
        public string UserAD { get; set; }
        public string SourceRolesCodes { get; set; }
        public string SourceFunctionForm { get; set; }
        public string FunctionType { get; set; }
        public string FunctionName { get; set; }
        public string FunctionTypeChild { get; set; }
        public string DestinationFunctionForm { get; set; }
        public string DestinationRolesCodes { get; set; }
        public int IDFlow { get; set; }
        public string MessageText { get; set; }
    }
}
