//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class UtilRule
    {
        public UtilRule()
        {
            this.UtilResponsibilityRules = new HashSet<UtilResponsibilityRule>();
        }
    
        public int IDRule { get; set; }
        public string RulesName { get; set; }
        public string Location { get; set; }
        public string Unit { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual ICollection<UtilResponsibilityRule> UtilResponsibilityRules { get; set; }
    }
}
