//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class UtilFlow
    {
        public UtilFlow()
        {
            this.UtilTransactionLogs = new HashSet<UtilTransactionLog>();
        }
    
        public int IDFlow { get; set; }
        public int FormSource { get; set; }
        public Nullable<int> ActionButton { get; set; }
        public Nullable<int> DestinationForm { get; set; }
        public Nullable<int> DestinationRole { get; set; }
        public string MessageText { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual UtilRolesFunction UtilRolesFunction { get; set; }
        public virtual UtilFunction UtilFunction { get; set; }
        public virtual UtilFunction UtilFunction1 { get; set; }
        public virtual ICollection<UtilTransactionLog> UtilTransactionLogs { get; set; }
    }
}
