//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class WagesProductionCardApprovalDetailViewGroup
    {
        public int RevisionType { get; set; }
        public string ProductionCardCode { get; set; }
        public string LocationCode { get; set; }
        public string UnitCode { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public string BrandGroupCode { get; set; }
        public string ProcessGroup { get; set; }
        public string GroupCode { get; set; }
        public Nullable<int> Worker { get; set; }
        public Nullable<float> Production { get; set; }
        public Nullable<float> UpahLain { get; set; }
        public Nullable<int> A { get; set; }
        public Nullable<int> C { get; set; }
        public Nullable<int> CH { get; set; }
        public Nullable<int> CT { get; set; }
        public Nullable<int> I { get; set; }
        public Nullable<int> LL { get; set; }
        public Nullable<int> LO { get; set; }
        public Nullable<int> LP { get; set; }
        public Nullable<int> MO { get; set; }
        public Nullable<int> PG { get; set; }
        public Nullable<int> S { get; set; }
        public Nullable<int> SB { get; set; }
        public Nullable<int> SKR { get; set; }
        public Nullable<int> SL4 { get; set; }
        public Nullable<int> SLP { get; set; }
        public Nullable<int> SLS { get; set; }
        public Nullable<int> T { get; set; }
        public Nullable<int> TL { get; set; }
    }
}
