//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class WagesProductionCardApprovalView
    {
        public long Row { get; set; }
        public Nullable<int> RevisionType { get; set; }
        public string ProductionCardCode { get; set; }
        public string LocationCode { get; set; }
        public string UnitCode { get; set; }
        public string BrandCode { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public Nullable<int> IDFlow { get; set; }
        public string Status { get; set; }
        public string UserAD { get; set; }
        public string RolesName { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> Shift { get; set; }
    }
}
