//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.Application.Resources.Views.MasterGenBrandGroup {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MasterGenBrandGroup {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MasterGenBrandGroup() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HMS.SKTIS.Application.Resources.Views.MasterGenBrandGroup.MasterGenBrandGroup", typeof(MasterGenBrandGroup).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Family.
        /// </summary>
        public static string lblFilterBrandFamily {
            get {
                return ResourceManager.GetString("lblFilterBrandFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Group Code.
        /// </summary>
        public static string lblFilterBrandGroupCode {
            get {
                return ResourceManager.GetString("lblFilterBrandGroupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string lblFilterClass {
            get {
                return ResourceManager.GetString("lblFilterClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack.
        /// </summary>
        public static string lblFilterPack {
            get {
                return ResourceManager.GetString("lblFilterPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bal/Box.
        /// </summary>
        public static string lblTitleBal {
            get {
                return ResourceManager.GetString("lblTitleBal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bal/Box.
        /// </summary>
        public static string lblTitleBalW {
            get {
                return ResourceManager.GetString("lblTitleBalW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Family.
        /// </summary>
        public static string lblTitleBrandFamily {
            get {
                return ResourceManager.GetString("lblTitleBrandFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Group Code.
        /// </summary>
        public static string lblTitleBrandGroupCode {
            get {
                return ResourceManager.GetString("lblTitleBrandGroupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tobacco Weight.
        /// </summary>
        public static string lblTitleCigarette {
            get {
                return ResourceManager.GetString("lblTitleCigarette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string lblTitleClassType {
            get {
                return ResourceManager.GetString("lblTitleClassType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string lblTitleDescription {
            get {
                return ResourceManager.GetString("lblTitleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack/Slof.
        /// </summary>
        public static string lblTitlePack {
            get {
                return ResourceManager.GetString("lblTitlePack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack.
        /// </summary>
        public static string lblTitlePackType {
            get {
                return ResourceManager.GetString("lblTitlePackType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack/Slof.
        /// </summary>
        public static string lblTitlePackW {
            get {
                return ResourceManager.GetString("lblTitlePackW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        public static string lblTitleRemark {
            get {
                return ResourceManager.GetString("lblTitleRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKT Brand Code.
        /// </summary>
        public static string lblTitleSKTBrandCode {
            get {
                return ResourceManager.GetString("lblTitleSKTBrandCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slof/Bal.
        /// </summary>
        public static string lblTitleSlof {
            get {
                return ResourceManager.GetString("lblTitleSlof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slof/Bal.
        /// </summary>
        public static string lblTitleSlofW {
            get {
                return ResourceManager.GetString("lblTitleSlofW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string lblTitleStatusActive {
            get {
                return ResourceManager.GetString("lblTitleStatusActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stick/Pack.
        /// </summary>
        public static string lblTitleStick {
            get {
                return ResourceManager.GetString("lblTitleStick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stick/Pack.
        /// </summary>
        public static string lblTitleStickW {
            get {
                return ResourceManager.GetString("lblTitleStickW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Update.
        /// </summary>
        public static string lblTitleUpdatedBy {
            get {
                return ResourceManager.GetString("lblTitleUpdatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Date.
        /// </summary>
        public static string lblTitleUpdatedDate {
            get {
                return ResourceManager.GetString("lblTitleUpdatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Group.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
    }
}
