//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.Application.Resources.Views.PlanningTPOTPK {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PlanningTPOTPK {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlanningTPOTPK() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HMS.SKTIS.Application.Resources.Views.PlanningTPOTPK.PlanningTPOTPK", typeof(PlanningTPOTPK).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JK Process.
        /// </summary>
        public static string btnProcess {
            get {
                return ResourceManager.GetString("btnProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WIP Stock.
        /// </summary>
        public static string btnWIP {
            get {
                return ResourceManager.GetString("btnWIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string lblFilterBrand {
            get {
                return ResourceManager.GetString("lblFilterBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string lblFilterLocation {
            get {
                return ResourceManager.GetString("lblFilterLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TPK No..
        /// </summary>
        public static string lblFilterTPK {
            get {
                return ResourceManager.GetString("lblFilterTPK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KPS Week.
        /// </summary>
        public static string lblFilterWeek {
            get {
                return ResourceManager.GetString("lblFilterWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KPS Year.
        /// </summary>
        public static string lblFilterYear {
            get {
                return ResourceManager.GetString("lblFilterYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocation.
        /// </summary>
        public static string lblTitleAllocation {
            get {
                return ResourceManager.GetString("lblTitleAllocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance.
        /// </summary>
        public static string lblTitleAttendance {
            get {
                return ResourceManager.GetString("lblTitleAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string lblTitleAvailable {
            get {
                return ResourceManager.GetString("lblTitleAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string lblTitleDate {
            get {
                return ResourceManager.GetString("lblTitleDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string lblTitleDay {
            get {
                return ResourceManager.GetString("lblTitleDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string lblTitleGroup {
            get {
                return ResourceManager.GetString("lblTitleGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productivity.
        /// </summary>
        public static string lblTitleHistorical {
            get {
                return ResourceManager.GetString("lblTitleHistorical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string lblTitleMasnual {
            get {
                return ResourceManager.GetString("lblTitleMasnual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string lblTitleProcess {
            get {
                return ResourceManager.GetString("lblTitleProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered.
        /// </summary>
        public static string lblTitleRegistered {
            get {
                return ResourceManager.GetString("lblTitleRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string lblTitleSystem {
            get {
                return ResourceManager.GetString("lblTitleSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string lblTitleTarget {
            get {
                return ResourceManager.GetString("lblTitleTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string lblTitleTotal {
            get {
                return ResourceManager.GetString("lblTitleTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Hours.
        /// </summary>
        public static string lblTitleWH {
            get {
                return ResourceManager.GetString("lblTitleWH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WIP.
        /// </summary>
        public static string lblTitleWIP {
            get {
                return ResourceManager.GetString("lblTitleWIP", resourceCulture);
            }
        }
    }
}
