ALTER TABLE [dbo].[ExePlantWorkerAbsenteeism] ADD CONSTRAINT [FK_ExePlantWorkerAbsenteeism_MstPlantEmpJobsDataAcv] FOREIGN KEY (EmployeeID) references MstPlantEmpJobsDataAll(EmployeeID)
ALTER TABLE [dbo].[ExePlantWorkerAssignment] ADD CONSTRAINT [FK_ExePlantWorkerAssignment_MstPlantEmpJobsDataAcv] FOREIGN KEY (EmployeeID) references MstPlantEmpJobsDataAll(EmployeeID)

ALTER TABLE [dbo].[MstPlantProductionGroup] WITH NOCHECK ADD CONSTRAINT [FK_MSTPLANTPRODUCTIONGROUP_RELATIONSHIP_97_MSTPLANTEMPJOBSDATAACV] FOREIGN KEY (InspectionLeader) references MstPlantEmpJobsDataAll(EmployeeID)
ALTER TABLE [dbo].[MstPlantProductionGroup] NOCHECK CONSTRAINT [FK_MSTPLANTPRODUCTIONGROUP_RELATIONSHIP_97_MSTPLANTEMPJOBSDATAACV]

ALTER TABLE [dbo].[MstPlantProductionGroup] WITH NOCHECK ADD CONSTRAINT [FK_MSTPLANTPRODUCTIONGROUP_RELATIONSHIP_98_MSTPLANTEMPJOBSDATAACV] FOREIGN KEY (Leader1) references MstPlantEmpJobsDataAll(EmployeeID)
ALTER TABLE [dbo].[MstPlantProductionGroup] NOCHECK CONSTRAINT [FK_MSTPLANTPRODUCTIONGROUP_RELATIONSHIP_98_MSTPLANTEMPJOBSDATAACV]

ALTER TABLE [dbo].[MstPlantProductionGroup] WITH NOCHECK ADD CONSTRAINT [FK_MSTPLANTPRODUCTIONGROUP_RELATIONSHIP_99_MSTPLANTEMPJOBSDATAACV] FOREIGN KEY (Leader2) references MstPlantEmpJobsDataAll(EmployeeID)
ALTER TABLE [dbo].[MstPlantProductionGroup] NOCHECK CONSTRAINT [FK_MSTPLANTPRODUCTIONGROUP_RELATIONSHIP_99_MSTPLANTEMPJOBSDATAACV]

ALTER TABLE [dbo].[PlanPlantAllocation] ADD CONSTRAINT [FK_PLANPLANTALLOCATION_REFERENCE_141_MSTPLANTEMPJOBSDATAACV] FOREIGN KEY (EmployeeID) references MstPlantEmpJobsDataAll(EmployeeID)

ALTER TABLE [dbo].[PlanPlantIndividualCapacityWorkHours] WITH NOCHECK ADD CONSTRAINT [FK_PLANPLANTINDIVIDUALCAPAC_RELATIONSHIP_112_MSTPLANTEMPJOBSDATAACV] FOREIGN KEY (EmployeeID) references MstPlantEmpJobsDataAll(EmployeeID)
ALTER TABLE [dbo].[PlanPlantIndividualCapacityWorkHours] NOCHECK CONSTRAINT [FK_PLANPLANTINDIVIDUALCAPAC_RELATIONSHIP_112_MSTPLANTEMPJOBSDATAACV]
