//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.Application.Resources.Views.MasterGenProcessSetting {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MasterGenProcessSetting {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MasterGenProcessSetting() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HMS.SKTIS.Application.Resources.Views.MasterGenProcessSetting.MasterGenProcessSet" +
                            "ting", typeof(MasterGenProcessSetting).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Group.
        /// </summary>
        public static string lblFilterBrandCode {
            get {
                return ResourceManager.GetString("lblFilterBrandCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string lblFilterProcess {
            get {
                return ResourceManager.GetString("lblFilterProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Group.
        /// </summary>
        public static string lblTitleBrandCode {
            get {
                return ResourceManager.GetString("lblTitleBrandCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process ID.
        /// </summary>
        public static string lblTitleIDProcess {
            get {
                return ResourceManager.GetString("lblTitleIDProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string lblTitleLocation {
            get {
                return ResourceManager.GetString("lblTitleLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Name.
        /// </summary>
        public static string lblTitleLocationName {
            get {
                return ResourceManager.GetString("lblTitleLocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty Worker.
        /// </summary>
        public static string lblTitleMaxWorker {
            get {
                return ResourceManager.GetString("lblTitleMaxWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Stk/Hour.
        /// </summary>
        public static string lblTitleMinStkHour {
            get {
                return ResourceManager.GetString("lblTitleMinStkHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string lblTitleProcess {
            get {
                return ResourceManager.GetString("lblTitleProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process ID.
        /// </summary>
        public static string lblTitleProcessID {
            get {
                return ResourceManager.GetString("lblTitleProcessID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Order.
        /// </summary>
        public static string lblTitleProcessOrder {
            get {
                return ResourceManager.GetString("lblTitleProcessOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Std Stk/Hour.
        /// </summary>
        public static string lblTitleStdStkHour {
            get {
                return ResourceManager.GetString("lblTitleStdStkHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOM Eblek.
        /// </summary>
        public static string lblTitleUOMEblek {
            get {
                return ResourceManager.GetString("lblTitleUOMEblek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Settings.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
    }
}
