//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.Application.Resources.Views.MasterMaintenanceConvert {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MasterMaintenanceConvert {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MasterMaintenanceConvert() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HMS.SKTIS.Application.Resources.Views.MasterMaintenanceConvert.MasterMaintenanceC" +
                            "onvert", typeof(MasterMaintenanceConvert).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string lblBtnDetail {
            get {
                return ResourceManager.GetString("lblBtnDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string lblTitleEquipmentToSparepartActive {
            get {
                return ResourceManager.GetString("lblTitleEquipmentToSparepartActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        public static string lblTitleEquipmentToSparepartRemark {
            get {
                return ResourceManager.GetString("lblTitleEquipmentToSparepartRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string lblTitleEquipmentToSparepartSource {
            get {
                return ResourceManager.GetString("lblTitleEquipmentToSparepartSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string lblTitleEquipmentToSparepartSourceDescription {
            get {
                return ResourceManager.GetString("lblTitleEquipmentToSparepartSourceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Code.
        /// </summary>
        public static string lblTitleEquipmentToSparepartSourceItemCode {
            get {
                return ResourceManager.GetString("lblTitleEquipmentToSparepartSourceItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Date.
        /// </summary>
        public static string lblTitleEquipmentToSparepartUpdateDate {
            get {
                return ResourceManager.GetString("lblTitleEquipmentToSparepartUpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Update.
        /// </summary>
        public static string lblTitleEquipmentToSparepartUserUpdate {
            get {
                return ResourceManager.GetString("lblTitleEquipmentToSparepartUserUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Destination.
        /// </summary>
        public static string lblTitlePopup {
            get {
                return ResourceManager.GetString("lblTitlePopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Description.
        /// </summary>
        public static string lblTitlePopupDescription {
            get {
                return ResourceManager.GetString("lblTitlePopupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Code.
        /// </summary>
        public static string lblTitlePopupItemCode {
            get {
                return ResourceManager.GetString("lblTitlePopupItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string lblTitlePopupQty {
            get {
                return ResourceManager.GetString("lblTitlePopupQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string lblTitleSparepartToSparepartActive {
            get {
                return ResourceManager.GetString("lblTitleSparepartToSparepartActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        public static string lblTitleSparepartToSparepartDestination {
            get {
                return ResourceManager.GetString("lblTitleSparepartToSparepartDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string lblTitleSparepartToSparepartDestinationDescription {
            get {
                return ResourceManager.GetString("lblTitleSparepartToSparepartDestinationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Code.
        /// </summary>
        public static string lblTitleSparepartToSparepartDestinationItemCode {
            get {
                return ResourceManager.GetString("lblTitleSparepartToSparepartDestinationItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string lblTitleSparepartToSparepartDestinationQty {
            get {
                return ResourceManager.GetString("lblTitleSparepartToSparepartDestinationQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        public static string lblTitleSparepartToSparepartRemark {
            get {
                return ResourceManager.GetString("lblTitleSparepartToSparepartRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string lblTitleSparepartToSparepartSource {
            get {
                return ResourceManager.GetString("lblTitleSparepartToSparepartSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string lblTitleSparepartToSparepartSourceDescription {
            get {
                return ResourceManager.GetString("lblTitleSparepartToSparepartSourceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Code.
        /// </summary>
        public static string lblTitleSparepartToSparepartSourceItemCode {
            get {
                return ResourceManager.GetString("lblTitleSparepartToSparepartSourceItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Date.
        /// </summary>
        public static string lblTitleSparepartToSparepartUpdatedDate {
            get {
                return ResourceManager.GetString("lblTitleSparepartToSparepartUpdatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Update.
        /// </summary>
        public static string lblTitleSparepartToSparepartUserUpdate {
            get {
                return ResourceManager.GetString("lblTitleSparepartToSparepartUserUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment to Sparepart.
        /// </summary>
        public static string lblTitleTabEquipmentToSparepart {
            get {
                return ResourceManager.GetString("lblTitleTabEquipmentToSparepart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sparepart to Sparepart.
        /// </summary>
        public static string lblTitleTabSparepartToSparepart {
            get {
                return ResourceManager.GetString("lblTitleTabSparepartToSparepart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Conversion.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
    }
}
