//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.SKTIS.Application.Resources.Views.MasterTPOFeeRate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MasterTPOFeeRate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MasterTPOFeeRate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HMS.SKTIS.Application.Resources.Views.MasterTPOFeeRate.MasterTPOFeeRate", typeof(MasterTPOFeeRate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Group Code.
        /// </summary>
        public static string lblFilterBrandGroupCode {
            get {
                return ResourceManager.GetString("lblFilterBrandGroupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TPO Location.
        /// </summary>
        public static string lblFilterTPOLocation {
            get {
                return ResourceManager.GetString("lblFilterTPOLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string lblFilterYear {
            get {
                return ResourceManager.GetString("lblFilterYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment.
        /// </summary>
        public static string lblTitleAttachment {
            get {
                return ResourceManager.GetString("lblTitleAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Date.
        /// </summary>
        public static string lblTitleEffectiveDate {
            get {
                return ResourceManager.GetString("lblTitleEffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired Date.
        /// </summary>
        public static string lblTitleExpiredDate {
            get {
                return ResourceManager.GetString("lblTitleExpiredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JKN.
        /// </summary>
        public static string lblTitleJKN {
            get {
                return ResourceManager.GetString("lblTitleJKN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JL1.
        /// </summary>
        public static string lblTitleJL1 {
            get {
                return ResourceManager.GetString("lblTitleJL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JL2.
        /// </summary>
        public static string lblTitleJL2 {
            get {
                return ResourceManager.GetString("lblTitleJL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JL3.
        /// </summary>
        public static string lblTitleJL3 {
            get {
                return ResourceManager.GetString("lblTitleJL3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JL4.
        /// </summary>
        public static string lblTitleJL4 {
            get {
                return ResourceManager.GetString("lblTitleJL4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Fee.
        /// </summary>
        public static string lblTitleManagementFee {
            get {
                return ResourceManager.GetString("lblTitleManagementFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memo Ref..
        /// </summary>
        public static string lblTitleMemoRef {
            get {
                return ResourceManager.GetString("lblTitleMemoRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productivity Incentives.
        /// </summary>
        public static string lblTitleProductivityIncentives {
            get {
                return ResourceManager.GetString("lblTitleProductivityIncentives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        public static string lblTitleRemark {
            get {
                return ResourceManager.GetString("lblTitleRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Update.
        /// </summary>
        public static string lblTitleUpdatedBy {
            get {
                return ResourceManager.GetString("lblTitleUpdatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Date.
        /// </summary>
        public static string lblTitleUpdatedDate {
            get {
                return ResourceManager.GetString("lblTitleUpdatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TPO Fee Rate.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
    }
}
